[Variables]

;-------------------------------------------------------------
;-------------------------------------------------------------

FontFace=Segoe UI Light 8

;-------------------------------------------------------------
;-------------------------------------------------------------

;FONT COLOR SETTINGS
;-------------------

;White=255,255,255
;Black=0,0,0
;Red=245,17,74
;LightRed=246,120,132
;Blue=23,27,245
;LightBlue=101,211,242
;Green=23,245,17
;LightGreen=126,250,153
;Orange=245,173,17
;Yellow=245,242,17
;Violet=189,17,245
;Pink=255,69,179

;Enter your font color here:
FontColor=23,245,17



;PROGRESS ROUNDLINE COLOR
;------------------------

;White=255,255,255
;Black=0,0,0
;Red=245,17,74
;LightRed=246,120,132
;Blue=23,27,245
;LightBlue=101,211,242
;Green=23,245,17
;LightGreen=126,250,153
;Orange=245,173,17
;Yellow=245,242,17
;Violet=189,17,245
;Pink=255,69,179

;Enter your progress roundline color here:
LineColor=23,245,17

;-------------------------------------------------------------
;-------------------------------------------------------------

;PLAYER SETTINGS
;---------------

;Suported players for now:

;Winamp: Player=Winamp
;Aimp: Player=AIMP
;Windows Media: Player=WMP
;MediaMonkey: Player=MediaMonkey
;iTunes: Player=iTunes

;Enter your player name here:
Player=WMP
